### PR TITLE
Fix actions that are a lua function causing an error with doom theme

### LINKED ISSUE #267: action no longer accepts a function
**Describe the bug**
Previously an entry could have a lua function as it's `action`. now it can't

**To Reproduce**
1. Use a lua function in your config
2. Click that entry on your dashboard
3. See error

```
E5108: Error executing lua: ...re/nvim/lazy/dashboard-nvim/lua/dashboard/theme/doom.lua:105: Expected lua string
stack traceback:
        [C]: in function 'cmd'
        ...re/nvim/lazy/dashboard-nvim/lua/dashboard/theme/doom.lua:105: in function <...re/nvim/lazy/dashboard-nvim/lua/d
ashboard/theme/doom.lua:101>
```

**Expected behavior**
It should run the lua function, same as it used to.

### PR DESCRIPTION
**Pull request by RoryNesbitt**
The doom theme was assuming all `action` entries were a string. Fixes #267

### CODE REVIEW

File: lua/dashboard/theme/doom.lua [hunk 1]
```diff
@@ -10,10 +10,13 @@ local function generate_center(config)
   do
     table.insert(lines, item.icon and item.icon .. item.desc or item.desc)
     table.insert(lines, '')
-    if item.key then
+    if item.key and type(item.action) == "string" then
```
Comment (glepnir) [inline lua/dashboard/theme/doom.lua:13]:
```suggestion
    if item.key and type(item.action) == 'string' then
```

File: lua/dashboard/theme/doom.lua [hunk 2]
```diff
@@ -102,7 +105,13 @@ local function generate_center(config)
     local curline = api.nvim_win_get_cursor(0)[1]
     local index = pos_map[curline - first_line]
     if index and config.center[index].action then
-      vim.cmd(config.center[index].action)
+      if type(config.center[index].action) == "string" then
```
Comment (glepnir) [inline lua/dashboard/theme/doom.lua:108]:
```suggestion
      if type(config.center[index].action) == 'string' then
```

File: lua/dashboard/theme/doom.lua [hunk 3]
```diff
@@ -102,7 +105,13 @@ local function generate_center(config)
...
+        vim.cmd(config.center[index].action)
+      elseif type(config.center[index].action) == "function" then
```
Comment (glepnir) [inline lua/dashboard/theme/doom.lua:110]:
```suggestion
      elseif type(config.center[index].action) == 'function' then
```

File: lua/dashboard/theme/doom.lua [hunk 4]
```diff
@@ -102,7 +105,13 @@ local function generate_center(config)
...
+        config.center[index].action()
+      else
+        print("Error with action, check your config")
```
Comment (glepnir) [inline lua/dashboard/theme/doom.lua:113]:
```suggestion
        print('Error with action, check your config')
```

File: lua/dashboard/theme/doom.lua [hunk 5]
```diff
@@ -10,10 +10,13 @@ local function generate_center(config)
   do
     table.insert(lines, item.icon and item.icon .. item.desc or item.desc)
     table.insert(lines, '')
-    if item.key then
+    if item.key and type(item.action) == 'string' then
       vim.keymap.set('n', item.key, function()
         vim.cmd(item.action)
       end, { buffer = config.bufnr, nowait = true, silent = true })
+    elseif item.key and type(item.action) == "function" then
+      vim.keymap.set('n', item.key, item.action,
```
Comment (glepnir) [inline lua/dashboard/theme/doom.lua:18]:
```suggestion
        vim.keymap.set(
           'n',
           item.key,
           item.action,
          { buffer = config.bufnr, nowait = true, silent = true }
      )
```

File: lua/dashboard/theme/doom.lua [hunk 6]
```diff
@@ -10,10 +10,13 @@ local function generate_center(config)
...
+      { buffer = config.bufnr, nowait = true, silent = true })
```
Comment (glepnir) [inline lua/dashboard/theme/doom.lua:19]:
```suggestion
```

**Review by glepnir — CHANGES_REQUESTED** [review]

File: lua/dashboard/theme/doom.lua [hunk 7]
```diff
@@ -10,10 +10,17 @@ local function generate_center(config)
...
       vim.keymap.set('n', item.key, function()
         vim.cmd(item.action)
       end, { buffer = config.bufnr, nowait = true, silent = true })
+    elseif item.key and type(item.action) == "function" then
+        vim.keymap.set(
+           'n',
+           item.key,
+           item.action,
+          { buffer = config.bufnr, nowait = true, silent = true }
+      )
```
Comment (glepnir) [inline lua/dashboard/theme/doom.lua:23]:
```suggestion
        )
```
